clc,clear
syms t psi(t) theta(t) L c m
syms gamma_dot_1(t) gamma_dot_2(t)
% gamma_dot_1 = theta_dot
% gamma_dot_2 = psi_dot


r_G = [(L+sin(theta)*L/2)*cos(psi); %[output:group:4162e54c] %[output:29fdfdbc]
       (L+sin(theta)*L/2)*sin(psi); %[output:29fdfdbc]
       -cos(theta)*L/2] %[output:group:4162e54c] %[output:29fdfdbc]
v_G = diff(r_G,t) %[output:1f06ebae]
a_G = simplify(diff(v_G,t)) %[output:2e4839f8]
a_G = subs(a_G,diff(theta,t),gamma_dot_1);
a_G = subs(a_G,diff(psi  ,t,t),c*gamma_dot_1) %[output:84050793]
a_G = subs(a_G,diff(psi  ,t),c*theta) %[output:1eb6cca1]
S1 = (1/2)*m*transpose(a_G)*a_G %[output:97779985]

simplify(diff(S1,diff(gamma_dot_2,t))) %[output:3e8d416f]

%[appendix]
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
%[output:29fdfdbc]
%   data: {"dataType":"symbolic","outputData":{"name":"r_G(t)","value":"\\left(\\begin{array}{c}\n\\cos \\left(\\psi \\left(t\\right)\\right)\\,{\\left(L+\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)}{2}\\right)}\\\\\n\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\left(L+\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)}{2}\\right)}\\\\\n-\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)}{2}\n\\end{array}\\right)"}}
%---
%[output:1f06ebae]
%   data: {"dataType":"symbolic","outputData":{"name":"v_G(t)","value":"\\begin{array}{l}\n\\left(\\begin{array}{c}\n\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;\\theta \\left(t\\right)}{2}-\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)\\\\\n\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)+\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;\\theta \\left(t\\right)}{2}\\\\\n\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;\\theta \\left(t\\right)}{2}\n\\end{array}\\right)\\\\\n\\mathrm{}\\\\\n\\textrm{where}\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_1 =L+\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)}{2}\n\\end{array}"}}
%---
%[output:2e4839f8]
%   data: {"dataType":"symbolic","outputData":{"name":"a_G(t)","value":"\\begin{array}{l}\n\\left(\\begin{array}{c}\n\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sigma_3 }{2}-\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\sigma_2 }{2}-\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\sigma_4 }{2}-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\sigma_5 }{2}-L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;\\theta \\left(t\\right)\\,\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)\\\\\n\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_3 }{2}-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\sigma_2 }{2}-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\sigma_4 }{2}+\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\sigma_5 }{2}+L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;\\theta \\left(t\\right)\\,\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)\\\\\n\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\sigma_3 }{2}+\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sigma_2 }{2}\n\\end{array}\\right)\\\\\n\\mathrm{}\\\\\n\\textrm{where}\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_1 =\\sin \\left(\\theta \\left(t\\right)\\right)+2\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_2 ={{\\left(\\frac{\\partial }{\\partial t}\\;\\theta \\left(t\\right)\\right)}}^2 \\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_3 =\\frac{\\partial^2 }{\\partial t^2 }\\;\\theta \\left(t\\right)\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_4 ={{\\left(\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)\\right)}}^2 \\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_5 =\\frac{\\partial^2 }{\\partial t^2 }\\;\\psi \\left(t\\right)\n\\end{array}"}}
%---
%[output:84050793]
%   data: {"dataType":"symbolic","outputData":{"name":"a_G(t)","value":"\\begin{array}{l}\n\\left(\\begin{array}{c}\n-\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\sigma_2 }{2}-L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)+\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}-\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}-\\frac{L\\,c\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,{\\dot{\\gamma} }_1 \\left(t\\right)}{2}\\\\\n-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,\\sigma_2 }{2}+L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)+\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}+\\frac{L\\,c\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sigma_1 \\,{\\dot{\\gamma} }_1 \\left(t\\right)}{2}\\\\\n\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}+\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}\n\\end{array}\\right)\\\\\n\\mathrm{}\\\\\n\\textrm{where}\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_1 =\\sin \\left(\\theta \\left(t\\right)\\right)+2\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_2 ={{\\left(\\frac{\\partial }{\\partial t}\\;\\psi \\left(t\\right)\\right)}}^2 \n\\end{array}"}}
%---
%[output:1eb6cca1]
%   data: {"dataType":"symbolic","outputData":{"name":"a_G(t)","value":"\\begin{array}{l}\n\\left(\\begin{array}{c}\n\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}-\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}-\\frac{L\\,c^2 \\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,{\\theta \\left(t\\right)}^2 \\,\\sigma_1 }{2}-\\frac{L\\,c\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\sigma_1 }{2}-L\\,c\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\theta \\left(t\\right)\\\\\n\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}-\\frac{L\\,c^2 \\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\theta \\left(t\\right)}^2 \\,\\sigma_1 }{2}+\\frac{L\\,c\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\sigma_1 }{2}+L\\,c\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\theta \\left(t\\right)\\\\\n\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}+\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}\n\\end{array}\\right)\\\\\n\\mathrm{}\\\\\n\\textrm{where}\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_1 =\\sin \\left(\\theta \\left(t\\right)\\right)+2\n\\end{array}"}}
%---
%[output:97779985]
%   data: {"dataType":"symbolic","outputData":{"name":"S1(t)","value":"\\begin{array}{l}\n\\frac{m\\,{{\\left(\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}-\\frac{L\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}+\\frac{L\\,c^2 \\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,{\\theta \\left(t\\right)}^2 \\,\\sigma_1 }{2}+\\frac{L\\,c\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\sigma_1 }{2}+L\\,c\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\theta \\left(t\\right)\\right)}}^2 }{2}+\\frac{m\\,{{\\left(\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}-\\frac{L\\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}-\\frac{L\\,c^2 \\,\\sin \\left(\\psi \\left(t\\right)\\right)\\,{\\theta \\left(t\\right)}^2 \\,\\sigma_1 }{2}+\\frac{L\\,c\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\sigma_1 }{2}+L\\,c\\,\\cos \\left(\\psi \\left(t\\right)\\right)\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,{\\dot{\\gamma} }_1 \\left(t\\right)\\,\\theta \\left(t\\right)\\right)}}^2 }{2}+\\frac{m\\,{{\\left(\\frac{L\\,\\cos \\left(\\theta \\left(t\\right)\\right)\\,{{\\dot{\\gamma} }_1 \\left(t\\right)}^2 }{2}+\\frac{L\\,\\sin \\left(\\theta \\left(t\\right)\\right)\\,\\frac{\\partial }{\\partial t}\\;{\\dot{\\gamma} }_1 \\left(t\\right)}{2}\\right)}}^2 }{2}\\\\\n\\mathrm{}\\\\\n\\textrm{where}\\\\\n\\mathrm{}\\\\\n\\;\\;\\sigma_1 =\\sin \\left(\\theta \\left(t\\right)\\right)+2\n\\end{array}"}}
%---
%[output:3e8d416f]
%   data: {"dataType":"symbolic","outputData":{"name":"ans(t)","value":"0"}}
%---
